# Generated by Django 3.1.3 on 2021-05-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bank',
            table='bank',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
    ]
