# Generated by Django 3.1.3 on 2021-05-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210529_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='ifsc',
            field=models.CharField(help_text='IFSC code of branch', max_length=21, primary_key=True, serialize=False),
        ),
    ]
