# Generated by Django 3.1.3 on 2021-05-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210529_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bank',
            field=models.ForeignKey(help_text='FK to Bank table', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='data.bank'),
        ),
    ]
