# Generated by Django 3.1.3 on 2021-05-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210530_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.AlterModelTable(
            name='bank',
            table=None,
        ),
        migrations.AlterModelTable(
            name='branch',
            table=None,
        ),
    ]
